### ISSUE TITLE
Support static contract variables in the debugger's variables view

### ISSUE THREAD

**Issue by csmuller** [neo-project/neo-debugger#105]
The variables view in the VSCode debugger mode does not show static member variables of smart contracts. It would definitely help to see the values of those variables in the variable view as well, when debugging a contract.

Here's example code. Not a valid use case though.
The local variable/parameter `i` shows up in the var view when stepping through `method`, but the static variables don't.

```
public class MyContract : SmartContract
{
    static int n = 10;
    static byte[] bytes = "0101".ToByteArray();

    public static BigInteger method(int i)
    {
        return (i + bytes.ToBigInteger()) * n;
    }
}
```

**Comment by devhawk** [comment]
fixed by #115
