### ISSUE TITLE
Ensure latest contract code is compiled when debug from invocation file   

### ISSUE THREAD

**Issue by kokahunter** [neo-project/neo-debugger#107]
Currently, if you start debugging from invocation file, it is not checked if latest code of smart contract is already build. That could lead to debugging old code and could cause confusion.

Proposal:
When starting debugging from invocation file, check that smart contract build is up to date. If not, build the contract automatically before start debugging.

**Comment by devhawk** [comment]
THis is a VSCode configuration issue. You need to specify a `preBuild` task in the launch configuration. Example: https://github.com/ngdenterprise/neo-registrar-sample/blob/master/.vscode/launch.json#L11
