### ISSUE TITLE
Allow to use multiple sequence points for the same opcode

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo-debugger#170]
Usually it is expected that one opcode will correspond to some point in a source file. However, neo-go compiler is able to inline functions (mostly syscalls), thus leading to a situation where a single opcode can correspond to 2 different function "calls".

We tried emitting `NOP` for such case https://github.com/nspcc-dev/neo-go/pull/2434 . I believe the best solution would be to have support for this in the debugger itself. I vaguely recall seing some `NOP`s in the C# compiler, but not sure if it was for the same reason.

**Comment by devhawk** [comment]
If there were multiple sequence points for a single opcode, how would the debugger choose which to display? 

I'm not familiar with the neo go compiler internals. In the NCCS Neo C# compiler, optimization and inlining are controlled via the `--no-optimize` and `--no-inline` flags. specifying those flags is similar to producing a debug build, which has the best debug experience. Not specifying those flags is similar to producing a release build, which has better performance but a degraded debug experience.

**Comment by roman-khimov** [comment]
We're trying to avoid adding more and more flags to the compiler as much as we can, but it looks like we can't avoid doing this here.

**Comment by devhawk** [comment]
> We're trying to avoid adding more and more flags to the compiler as much as we can, but it looks like we can't avoid doing this here.

Controlling optimization level via CLI flags is pretty standard practice for compilers in my experience
