### ISSUE TITLE
Debugged function return value?

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-debugger#176]
I was trying to help a discord user with a smart contract question and thought neo-debugger could be suitable. So I wanted to debug the following contract function
```python
@public
def test() -> bool:
    tx = cast(Transaction, script_container)
    return tx.script[0] == 0xc2
```
but then realized I couldn't see what was actually returned. Is there a place I should be able to see the returned value from the function?

**Comment by devhawk** [comment]
The gas consumed + any result will show up in the debug console window. Here's an example: 
<img width="521" alt="image" src="https://user-images.githubusercontent.com/8965/184701182-003ce691-56da-478f-9624-36bde879bc57.png">

Note, you can specify the expected return type via the [`return-types`](https://github.com/neo-project/neo-debugger/blob/master/docs/debug-config-reference.md#return-types) config property. Once the storage schema work is merged, the debugger will be able to do a better job automatically rendering operation output
