### ISSUE TITLE
Is debugger support serialize/deserialize now?

### ISSUE THREAD

**Issue by Lichen9618** [neo-project/neo-debugger#3]
I stack at function like

                Map<BigInteger, byte[]> WhiteList = new Map<BigInteger, byte[]>();

                int number = args.Length;
                for (int i = 0; i < number; i++)
                {
                    WhiteList[i] = (byte[])args[i]; 
                }
                Storage.Put(Storage.CurrentContext, "WhiteList", 
                Neo.SmartContract.Framework.Helper.Serialize(WhiteList));

Is debugger support  serialize now?
It can work on my private-net

**Comment by devhawk** [comment]
I just released the latest version (0.9) of the debugger on the VSCode marketplace. It supports serialize/deserialize now.
